version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      FRONTEND_URL: http://frontend:80
    networks:
      - app-network

  pinger:
    build:
      context: ./pinger
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"
    environment:
      # http://backend:8080/containers
      BACKEND_NAME: backend
      BACKEND_PORT: 8080
      BACKEND_ROUTE: containers

  db:
    build:
      context: ./database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend/docker-monitoring-frontend
      args:
        - REACT_APP_BACKEND_URL=http://backend:8080
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
